# ServiceAccount for CSI controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
---
# ServiceAccount for CSI node plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-csi-node
  namespace: kube-system
